In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/creditcardfraud/creditcard.csv


In [2]:
data = pd.read_csv('/kaggle/input/creditcardfraud/creditcard.csv')

# EDA

In [3]:
data.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [4]:
data.shape

(284807, 31)

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype  
---  ------  --------------   -----  
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     28

In [6]:
import matplotlib.pyplot as plt

In [7]:
X = data.drop("Class", axis=1)
y = data["Class"]

In [8]:
y.value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

## Balance data through SMOTE

In [9]:
from imblearn.over_sampling import SMOTE

sm = SMOTE()

X_resampled, y_resampled = sm.fit_resample(X, y)

In [10]:
y_resampled.value_counts()

Class
0    284315
1    284315
Name: count, dtype: int64

## Standardize Data

In [11]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_resampled)

In [12]:
pd.DataFrame(X_scaled).head()

0         1         2         3         4         5         6   \
0 -1.823927  0.206521 -0.547709  1.003888 -0.303098  0.313245  0.692918   
1 -1.823927  0.673072 -0.454605  0.620076 -0.598577  0.409240  0.373922   
2 -1.823906  0.206787 -0.895857  0.880294 -0.620301  0.273511  1.476494   
3 -1.823906  0.278476 -0.578597  0.883498 -1.015249  0.392292  1.152493   
4 -1.823885  0.243378 -0.286603  0.843936 -0.612913  0.296647  0.478321   

         7         8         9   ...        20        21        22        23  \
0  0.555381 -0.037707  0.762164  ...  0.065239 -0.146072  0.246059 -0.105400   
1  0.499709 -0.040452  0.484378  ... -0.245714 -0.219031 -0.541779  0.105423   
2  0.651874 -0.007627 -0.080528  ...  0.330661 -0.052422  0.670570  0.909965   
3  0.555033  0.018572 -0.023271  ... -0.380531 -0.177720  0.011761 -0.184893   
4  0.617163 -0.112256  0.965812  ...  0.217691 -0.142951  0.693434 -0.132265   

         24        25        26        27        28        29  
0  0.225475  0.165801 -0.485859  0.055188 -0.147936  0.245344  
1 -0.526956  0.228853  0.217970 -0.094286 -0.062469 -0.421822  
2 -1.173323 -0.578759 -0.374102 -0.142910 -0.240382  1.285346  
3 -2.072846  1.012625 -0.559175 -0.019092  0.049170  0.126740  
4  0.362984 -0.380236  1.058959  0.145227  0.416327 -0.116232  

[5 rows x 30 columns]

In [13]:
y_scaled = y_resampled.astype(bool).values

In [14]:
y_scaled

array([False, False, False, ...,  True,  True,  True])

# Training Models

In [15]:
# from sklearn.ensemble import IsolationForest #iForest
# from sklearn.neighbors import LocalOutlierFactor #LOF
# from sklearn.covariance import EllipticEnvelope #Robust Coveriance
# from sklearn.svm import OneClassSVM #OCSVM
# from sklearn.metrics import classification_report, accuracy_score, f1_score
# from sklearn.model_selection import cross_val_score, KFold

In [16]:
# models = {
#     "Isolation Forest": IsolationForest(n_estimators=100, contamination='auto', random_state=42),
#     "Local Outlier Factor": LocalOutlierFactor(n_neighbors=20, contamination='auto'),
#     "Robust Covariance": EllipticEnvelope(support_fraction=1., contamination=0.1),
#     "One-Class SVM": OneClassSVM(kernel='linear', gamma=0.001, nu=0.05),
# }

In [17]:
# kf = KFold(n_splits=10)
# for model_name, model in models.items():
#     results = cross_val_score(model, X_scaled, y_scaled, scoring="f1", cv=kf)
#     print(f"\n\n{model_name}:\n{results}")

In [18]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier

In [19]:
# Decision Tree
dt_classifier = DecisionTreeClassifier()
# dt_classifier.fit(X_scaled, y_scaled)
# Random Forest
rf_classifier = RandomForestClassifier()
# rf_classifier.fit(X_scaled, y_scaled)
# XGBoost
xgb_classifier = XGBClassifier()
# xgb_classifier.fit(X_scaled, y_scaled)
# Extra Trees
et_classifier = ExtraTreesClassifier()
# et_classifier.fit(X_scaled, y_scaled)
# LightGBM
lgbm_classifier = LGBMClassifier()
# lgbm_classifier.fit(X_scaled, y_scaled)

In [20]:
from sklearn.model_selection import cross_val_score, KFold

kf = KFold(n_splits=5)

dt_results = cross_val_score(dt_classifier, X_scaled, y_scaled, scoring="f1", cv=kf)
print(f"\nDecision Tree:\n{dt_results}\n")
rf_results = cross_val_score(rf_classifier, X_scaled, y_scaled, scoring="f1", cv=kf)
print(f"\nRandom Forest:\n{rf_results}\n")
xgb_results = cross_val_score(xgb_classifier, X_scaled, y_scaled, scoring="f1", cv=kf)
print(f"\nXGBoost:\n{xgb_results}\n")
et_results = cross_val_score(et_classifier, X_scaled, y_scaled, scoring="f1", cv=kf)
print(f"\nExtra Trees:\n{et_results}\n")
lgbm_results = cross_val_score(lgbm_classifier, X_scaled, y_scaled, scoring="f1", cv=kf)
print(f"\nLightGBM:\n{lgbm_results}\n")


Decision Tree:
[0.00430204 0.05555556 0.70186552 0.99930046 0.99927845]


Random Forest:
[0.00441121 0.76025918 0.7100617  0.99998681 0.99998681]


XGBoost:
[0.00424935 0.0688172  0.68154212 1.         1.        ]


Extra Trees:
[0.00965893 0.64468864 0.99907077 1.         1.        ]


LightGBM:
[0.00425299 0.06607847 0.72592231 0.99990327 0.99988568]

