In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
# data = pd.read_csv('/kaggle/input/creditcardfraud/creditcard.csv')
data = pd.read_csv('creditcard.csv')

# EDA

In [3]:
data.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [4]:
data.shape

(284807, 31)

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype  
---  ------  --------------   -----  
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     28

In [6]:
import matplotlib.pyplot as plt

In [7]:
X = data.drop("Class", axis=1)
y = data["Class"]

In [8]:
y.value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

## Balance data through SMOTE

In [9]:
from imblearn.over_sampling import SMOTE

sm = SMOTE()

X_resampled, y_resampled = sm.fit_resample(X, y)

In [10]:
y_resampled.value_counts()

Class
0    284315
1    284315
Name: count, dtype: int64

## Standardize Data

In [11]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
# X_scaled = scaler.fit_transform(X_resampled)
X_scaled = scaler.fit_transform(X)

In [12]:
pd.DataFrame(X_scaled).head()

0         1         2         3         4         5         6   \
0 -1.996583 -0.694242 -0.044075  1.672773  0.973366 -0.245117  0.347068   
1 -1.996583  0.608496  0.161176  0.109797  0.316523  0.043483 -0.061820   
2 -1.996562 -0.693500 -0.811578  1.169468  0.268231 -0.364572  1.351454   
3 -1.996562 -0.493325 -0.112169  1.182516 -0.609727 -0.007469  0.936150   
4 -1.996541 -0.591330  0.531541  1.021412  0.284655 -0.295015  0.071999   

         7         8         9   ...        20        21        22        23  \
0  0.193679  0.082637  0.331128  ...  0.326118 -0.024923  0.382854 -0.176911   
1 -0.063700  0.071253 -0.232494  ... -0.089611 -0.307377 -0.880077  0.162201   
2  0.639776  0.207373 -1.378675  ...  0.680975  0.337632  1.063358  1.456320   
3  0.192071  0.316018 -1.262503  ... -0.269855 -0.147443  0.007267 -0.304777   
4  0.479302 -0.226510  0.744326  ...  0.529939 -0.012839  1.100011 -0.220123   

         24        25        26        27        28        29  
0  0.110507  0.246585 -0.392170  0.330892 -0.063781  0.244964  
1 -0.561131  0.320694  0.261069 -0.022256  0.044608 -0.342475  
2 -1.138092 -0.628537 -0.288447 -0.137137 -0.181021  1.160686  
3 -1.941027  1.241904 -0.460217  0.155396  0.186189  0.140534  
4  0.233250 -0.395202  1.041611  0.543620  0.651816 -0.073403  

[5 rows x 30 columns]

In [13]:
# y_scaled = y_resampled.astype(bool).values
y_scaled = y.astype(bool).values

In [14]:
y_scaled

array([False, False, False, ..., False, False, False])

# Training Models

In [15]:
# from sklearn.ensemble import IsolationForest #iForest
# from sklearn.neighbors import LocalOutlierFactor #LOF
# from sklearn.covariance import EllipticEnvelope #Robust Coveriance
# from sklearn.svm import OneClassSVM #OCSVM
# from sklearn.metrics import classification_report, accuracy_score, f1_score
# from sklearn.model_selection import cross_val_score, KFold

In [16]:
# models = {
#     "Isolation Forest": IsolationForest(n_estimators=100, contamination='auto', random_state=42),
#     "Local Outlier Factor": LocalOutlierFactor(n_neighbors=20, contamination='auto'),
#     "Robust Covariance": EllipticEnvelope(support_fraction=1., contamination=0.1),
#     "One-Class SVM": OneClassSVM(kernel='linear', gamma=0.001, nu=0.05),
# }

In [17]:
# kf = KFold(n_splits=10)
# for model_name, model in models.items():
#     results = cross_val_score(model, X_scaled, y_scaled, scoring="f1", cv=kf)
#     print(f"\n\n{model_name}:\n{results}")

In [18]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier

In [19]:
# Decision Tree
dt_classifier = DecisionTreeClassifier()
# dt_classifier.fit(X_scaled, y_scaled)
# Random Forest
rf_classifier = RandomForestClassifier()
# rf_classifier.fit(X_scaled, y_scaled)
# XGBoost
xgb_classifier = XGBClassifier()
# xgb_classifier.fit(X_scaled, y_scaled)
# Extra Trees
et_classifier = ExtraTreesClassifier()
# et_classifier.fit(X_scaled, y_scaled)
# LightGBM
lgbm_classifier = LGBMClassifier()
# lgbm_classifier.fit(X_scaled, y_scaled)

In [20]:
from sklearn.model_selection import cross_val_score, KFold

kf = KFold(n_splits=5)

dt_results = cross_val_score(dt_classifier, X_scaled, y_scaled, scoring="f1", cv=kf)
print(f"\nDecision Tree:\n{dt_results}\n")
rf_results = cross_val_score(rf_classifier, X_scaled, y_scaled, scoring="f1", cv=kf)
print(f"\nRandom Forest:\n{rf_results}\n")
xgb_results = cross_val_score(xgb_classifier, X_scaled, y_scaled, scoring="f1", cv=kf)
print(f"\nXGBoost:\n{xgb_results}\n")5
et_results = cross_val_score(et_classifier, X_scaled, y_scaled, scoring="f1", cv=kf)
print(f"\nExtra Trees:\n{et_results}\n")
lgbm_results = cross_val_score(lgbm_classifier, X_scaled, y_scaled, scoring="f1", cv=kf)
print(f"\nLightGBM:\n{lgbm_results}\n")


Decision Tree:
[0.19907407 0.68421053 0.692607   0.59375    0.63694268]


Random Forest:
[0.82634731 0.81944444 0.82905983 0.78350515 0.8125    ]


XGBoost:
[0.81437126 0.84563758 0.8245614  0.8        0.82442748]


Extra Trees:
[0.8136646  0.83561644 0.84978541 0.80808081 0.8       ]

[LightGBM] [Info] Number of positive: 335, number of negative: 227510
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.033877 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 7650
[LightGBM] [Info] Number of data points in the train set: 227845, number of used features: 30
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.001470 -> initscore=-6.520819
[LightGBM] [Info] Start training from score -6.520819
[LightGBM] [Info] Number of positive: 408, number of negative: 227437
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.035349 seconds.
You can set `force_col_wise=true` to remove 